[package]
name = "netlink_testing"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
rtnetlink = "0"
futures-util = "0.3"
derivative = "2"
zerocopy = "0"