[package]
name = "lts_node"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
anyhow = "1"
env_logger = "0"
log = "0"
serde = { version = "1.0", features = ["derive"] }
axum = "0.6"
lqos_bus = { path = "../../lqos_bus" }
serde_json = "1"
pgdb = { path = "../pgdb" }
dryoc = { version = "0.5", features = ["serde"] }
once_cell = "1"